stages:
  - build

build-docs:
  stage: build
  tags:
    - py3.8
  script:
    - poetry install --extras "dev docs"
    - poetry run mkdocs build
    - cp -r site /home/wwwtiqidocs/public/pytrans
#   rules:
#     - if: $CI_COMMIT_BRANCH == "master"
