[tool.poetry]
name = "pytrans"
version = "2.0.0"
description = "Transport waveform-related generation and analysis utilities"
authors = ["cmordini <cmordini@phys.ethz.ch>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
numpy = "^1.22.2"
scipy = "^1.8.0"
cvxpy = "^1.1.18"
Mosek = "^9.3.14"
colorama = "^0.4.4"
matplotlib = "^3.5.1"
PyQt5 = "^5.15.6"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
