#!/usr/bin/env python3
# Simulates Coulomb-repulsion effects for splitting well
# Filename must match the one generated by load_and_split.py

import sys
sys.path.append("../")
from pytrans import *
import splitting as sp

# Recent splitting
# wf_path = os.path.join(os.pardir, "waveform_files", "load_split_2Be1Ca_2017_02_22_v02.dwc.json")

## Decent splitting routine
wf_path = os.path.join(os.pardir, "waveform_files", "load_split_2Be1Ca_2017_02_21_v04.dwc.json")
wf_label = "split apart, offset = 0.000e+00 V/m"

## Older splitting routine
#wf_path = os.path.join(os.pardir, "waveform_files", "load_split_2Be1Ca_2017_01_25_v02.dwc.json")
#wf_label = "-3.333e-06"

def split_coulomb_test():
    wfs = WaveformSet(waveform_file=wf_path)
    try:
        wp = wfs.find_waveform(wf_label).samples
    except AttributeError:
        print(wfs)
    # wp = wfs.find_waveform("1.667").samples    
    # st()
    file_date = wf_path.split('.')[-3].split('Ca')[-1]
    sp.plot_split_dfo(wp, parallel_solve=True, savefig=file_date)

if __name__ == "__main__":
    split_coulomb_test()
    # split_coulomb_test()
